{
   /* Build overlay of haskell packages as used by your projects:
    *
    * Example:
    *
    * let
    *   cheopslab-pkg = import (builtins.fetchGit {...});
    *   overlay = [
    *     (cheopslab-pkg.mk-overlay {})
    *     ...
    *   ];
    */
   mk-overlay = {ghcVersion ? "ghc8107"}:
     self: super:
     {
       # Defining cheopslab hierarchy.
       cheopslab = {
         # Tools for building docker images.
         docker = import ./nix/docker.nix self;
         # Define haskell packages we use
         haskellPackages = super.haskell.packages.${ghcVersion}.override {
           overrides = hfinal: hprev:
             with super.haskell.lib;
             # auto-generated by nix/haskellPackages/update.sh
             (import ./nix/default.nix) super.haskell.lib hprev
         };
         # Library with helper functions.
         lib = (import ./nix/lib.nix) self super;
       };
     };
}
